config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :empresas


  root 'empresas#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/empresa.rb
class Empresa < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/empresas_controller.rb
class EmpresasController < ApplicationController
  before_action :set_empresa, only: [:show, :edit, :update, :destroy]

  # GET /empresas
  # GET /empresas.json
  def index
    @empresas = Empresa.all
  end

  # GET /empresas/1
  # GET /empresas/1.json
  def show
  end

  # GET /empresas/new
  def new
    @empresa = Empresa.new
  end

  # GET /empresas/1/edit
  def edit
  end

  # POST /empresas
  # POST /empresas.json
  def create
    @empresa = Empresa.new(title: params[:title])

    @empresa.save
    respond_to do |format|
      format.js
    end

    #respond_to do |format|
      #if @empresa.save
        #format.html { redirect_to @empresa, notice: 'Empresa was successfully created.' }
        #format.json { render :show, status: :created, location: @empresa }
      #else
        #format.html { render :new }
        #format.json { render json: @empresa.errors, status: :unprocessable_entity }
      #end
    #end
  end

  # PATCH/PUT /empresas/1
  # PATCH/PUT /empresas/1.json
  def update
    respond_to do |format|

      format.js
   

      #if @empresa.update(empresa_params)
        #format.html { redirect_to @empresa, notice: 'Empresa was successfully updated.' }
        #format.json { render :show, status: :ok, location: @empresa }
      #else
        #format.html { render :edit }
        #format.json { render json: @empresa.errors, status: :unprocessable_entity }
      #end
    end
  end

  # DELETE /empresas/1
  # DELETE /empresas/1.json
  def destroy

    @empresa.destroy

    respond_to do |format|
      format.js
    end
    #respond_to do |format|
      #format.html { redirect_to empresas_url, notice: 'Empresa was successfully destroyed.' }
      #format.json { head :no_content }
    #end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_empresa
      @empresa = Empresa.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def empresa_params
      params.require(:empresa).permit(:title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/empresas_helper.rb
module EmpresasHelper
end

app/views/empresas/_empresa.html.erb
 <li id= '<%= empresa.id  %>' >
            <ul>
              <li>
                <%= empresa.title %>
              </li>
              <li>
                <%= link_to 'Destroy', empresa, method: :delete, remote: true%>
              </li>
               <li>
                <%= link_to 'Edit', edit_empresa_path(empresa), data: {remote: true} %>
              </li>
            </ul> 
            
            
            

</li>

app/views/empresas/_form.html.erb
<%= form_with(model: empresa, local: true) do |form| %>
  <% if empresa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(empresa.errors.count, "error") %> prohibited this empresa from being saved:</h2>

      <ul>
      <% empresa.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :empresa_title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/empresas/create.js.erb
$('#empresas').append( "<%=  j render @empresa  %>");

app/views/empresas/destroy.js.erb
$('#<%= @empresa.id %>').toggle(400);

app/views/empresas/edit.html.erb
<h1>Editing Empresa</h1>

<%= render 'form', empresa: @empresa %>

<%= link_to 'Show', @empresa %> |
<%= link_to 'Back', empresas_path %>

app/views/empresas/edit.js.erb
$('#myModal').modal('show');

$('#modal-body').append( "<%=  j render 'form', empresa: @empresa, data: {remote: true}  %>");

app/views/empresas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Empresas</h1>

<!--<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @empresas.each do |empresa| %>
      <tr>
        <td><%= empresa.title %></td>
        <td><%= link_to 'Show', empresa %></td>
        <td><%= link_to 'Edit', edit_empresa_path(empresa) %></td>
        <td><%= link_to 'Destroy', empresa, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>-->

<br>




<div class="container">
  <div class="row">
    <div class="col-md-6">

      <ul id="empresas">
        <% @empresas.each do |empresa| %>

           <li id= '<%= empresa.id  %>' >
             <ul>
                <li>
                  <%= empresa.title %>
                </li>
                <li>
                  <%= link_to 'Destroy', empresa, method: :delete, data: {remote: true} %>
                </li>
                <li>
                  <%= link_to 'Edit', edit_empresa_path(empresa), data: {remote: true} %>
                </li>
               
             </ul> 
            
            
            

           </li>

        <% end %>
      </ul>

    </div>

    <div class="col-md-6">
    


      <%= form_with(model: @empresa) do |form| %>
        

        <div class="field">
          <%= form.label :title %>
          <%= form.text_field :title, id: :empresa_title %>
        </div>

        <div class="actions">
          <%= form.submit %>
        </div>
      <% end %>
      
    </div>

  </div>
</div>

<!-- Button trigger modal -->


<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" id="modal-body">
        
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

app/views/empresas/new.html.erb
<h1>New Empresa</h1>

<%= render 'form', empresa: @empresa %>

<%= link_to 'Back', empresas_path %>

app/views/empresas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @empresa.title %>
</p>

<%= link_to 'Edit', edit_empresa_path(@empresa) %> |
<%= link_to 'Back', empresas_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Prueba30</title>
    <%= csrf_meta_tags %>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

   <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<p class="notice"><%= notice %></p>
     <p class="alert"><%= alert %></p>
    <%= yield %>

 
  </body>
</html>